sudo: required
services:
  - docker

before_install:
  - docker build -t iddqdkfa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iddqdkfa/docker-react npm run test -- --watchAll=false
#test
